### ISSUE TITLE
請問下這個庫大概的原理？

### ISSUE THREAD

**Issue by zzz6519003** [chengjun/iching#3]

**Comment by chengjun** [comment]
实现易经蓍草卜卦的整个过程。《周易.系辞上传》： 
“大衍之数五十，其用四十有九。分而为二以象两，挂一以象三， 揲之以四以象四时，归奇于扐以象闰，五岁再闰，故再扐而后挂。 天一地二，天三地四，天五地六，天七地八，天九地十。天数五，地数五，五位相得而各有合。天数二十有五，地数三十，凡天地之数五十有五。此所以成变化而行鬼神也。”

**Comment by chengjun** [comment]
作者：小司马
链接：https://www.zhihu.com/question/33646380/answer/131429959
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

“大衍之數五十，其用四十有九。”“衍”就是“演”，推演的意思。用以推演占卦的数便是“大衍之數”，总共为50，使用的数是49。在占卦时，蓍草要准备50根，然后拿出一根不用，用剩下的49根推算。“分而爲二以象兩，掛一以象三，揲之以四以象四時，歸奇於扐以象閏。”“分而爲二以象兩”的意思是将49根蓍草随机分为两份，这二分就是象征阴阳两仪的二分。“掛一以象三”是指从任一份里取出一根蓍草，与剩下的两份构成三分之势，以此来象征“天地人”三才。“揲之以四以象四時”，“揲”就是用手清点，这句是说接下来就要以4为单位来清点这两份蓍草了(根数总和为48)。为什么以4为单位呢？是要象征一年的四季。“歸奇於扐以象閏”中的“奇”是余数，“扐”是手指之间。把两份蓍草清点完，两边一定都有剩余的部分，即使是余下4根也算余数。古人把两边清点余下的蓍草就夹于指间，用以象征闰月。这句话一共有四步，每一小句是一个步骤，古人称为“四營”。 后面说了，“四營而成易，十有八變而成卦”，也就是“分二”、“掛一”、“揲四”和“歸奇”这“四營”加起来算是成了一变，“易”就是变。那么要变几次才能成一个“卦”呢？“十有八變而成卦”，变上十八回才能得到我们的卦。这样以来，18除6得3，也就是说3变得到一个爻。这个信息在原文里省去了，古人没说变几回才能得到一个爻，但是我们后人不要死板，仔细一推算就能悟出了。这样以来，蓍草占卜的程序已经清楚了，即四营成一变，三变成一爻，六爻十八变成一卦。“五歲再閏，故再扐而後卦。”是说五年有两个闰月，所以将两份的归奇余数（以4分组后剩下的余数）都合并，然后再进行下一变的四营程序。“再扐”指合并两份的归奇余数。那么具体怎样去确定每一个爻呢? 这其中就有数学道理了。让我们先来模拟一下古人占卜的过程，进而推算其可能出现多少种结果。首先说明一下程序分步，分二、挂一、揲四、归奇为四营，四营成一变，三变成一爻，十八变成一卦。【第一变】挂一后的两份总数为： 49－1=48（根）  48÷4无余数，则表明揲四后归奇的蓍草总数是4或8根，即两种情况：①    一边根数分别为1、2、3，另一边对应分别为3、2、1；②    一边根数为4，另一边也是4。除去归奇蓍草后还有48－4=44根（① 的3种结果）或48－8=40根（② 的1种结果）于是，变之二会有两种情况。  【第二变】情况1（变之一剩下44根）：   挂一后的两份总数为： 44－1=43（根）   43÷4余数为3，则表明揲四后归奇的蓍草总数是3或7根，即两种情况：①    一边根数分别为1、2，另一边对应分别为2、1；②    一边根数分别为3、4，另一边对应分别为4、3。   除去归奇蓍草后还有43－3=40根（① 的2种结果）或43－7=36根（② 的2种结果）情况2（变之一剩下40根）：挂一后的两份总数为： 40－1=39（根）39÷4余数为3，则表明揲四后归奇的蓍草总数是3或7根，即两种情况：①    一边根数分别为1、2，另一边对应分别为2、1；②    一边根数分别为3、4，另一边对应分别为4、3。除去归奇蓍草后还有39－3=36根（① 的2种结果）或39－7=32根（② 的2种结果）综上所述，变之二最终剩下的蓍草数为40、36或32根。于是，变之三会有三种情况。【第三变】情况1（变之二剩下40根）：   挂一后的两份总数为： 40－1=39（根）   39÷4余数为3，则表明揲四后归奇的蓍草总数是3或7根，即两种情况：①    一边根数分别为1、2，另一边对应分别为2、1；②    一边根数分别为3、4，另一边对应分别为4、3。   除去归奇蓍草后还有39－3=36根（① 的2种结果）或39－7=32根（② 的2种结果）情况2（变之二剩下36根）：挂一后的两份总数为： 36－1=35（根）35÷4余数为3，则表明揲四后归奇的蓍草总数是3或7根，即两种情况：①    一边根数分别为1、2，另一边对应分别为2、1；②    一边根数分别为3、4，另一边对应分别为4、3。除去归奇蓍草后还有35-3=32根（① 的2种结果）或35－7=28根（② 的2种结果）情况3（变之二剩下32根）：挂一后的两份总数为： 32－1=31（根）31÷4余数为3，则表明揲四后归奇的蓍草总数是3或7根，即两种情况：①    一边根数分别为1、2，另一边对应分别为2、1；②   一边根数分别为3、4，另一边对应分别为4、3。除去归奇蓍草后还有31－3=28根（① 的2种结果）或31－7=24根（② 的2种结果）     综上所述，变之三最终剩下的蓍草数为36、32、28或24根（如图所示）。三变共计有64种结果，其中得36的结果有12种，得32的结果有28种，得28的结果有20种，得24的结果有4种。
